@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjlhYWMyMDliOWQ2YmJhY2U1YjRlMGUxIiwiaWF0IjoxNzcyNzk4NTA1LCJleHAiOjE3NzM2NjI1MDV9.Hv8kTigJEs6BZd0Q8uRWOLUrp__FMvADjU1idRqzW7w

GET http://localhost:3000/api/characters
Authorization: Bearer {{ token }}

###
GET http://localhost:3000/api/characters?page=3&limit=4
Authorization: Bearer {{ token }}

###
POST http://localhost:3000/api/characters
Content-Type: application/json
Authorization: Bearer {{ token }}

    {
      "name": "Rexxar",
      "img": "https://wow.zamimg.com/uploads/screenshots/normal/1202262-rexxar.jpg",
      "age": 50,
      "species": "Orco",
      "specialTraits": [
        "Bestia domada",
        "Lanzamiento de hachas",
        "Llamada de la bestia"
      ],
      "role": "Cazador",
      "firstAppearance": "World of Warcraft: The Burning Crusade"
    }

###
GET http://localhost:3000/api/characters/69a02b6a21dd4ffc04c140bc
Authorization: Bearer {{ token }}

###

PUT http://localhost:3000/api/characters/69aac2ebb9d6bbace5b4e0fa
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "age": 71,
    "specialTraits": [
        "Bestia domada",
        "Lanzamiento de hachas",
        "Trampas y Explosivos"
        ]
}   

###
DELETE http://localhost:3000/api/characters/69aac297b9d6bbace5b4e0ee
Authorization: Bearer {{ token }}